import { v4 } from "uuid";

export const achievements = [
  {
    id: v4(),
    difficulty: "Very Easy",
    bonus: 1,
    title: "Roll your first die",
    desc: "Just press the button",
    completed: false,
    achieveNo: 1,
  },
  {
    id: v4(),
    difficulty: "Very Easy",
    bonus: 1,
    title: "Upgrade your first die",
    desc: "I wonder what this button does",
    completed: false,
    achieveNo: 2,
  },
  {
    id: v4(),
    difficulty: "Very Easy",
    bonus: 1,
    title: "Posess a whole Benjamin",
    desc: "High schoolers are jealous of you",
    completed: false,
    achieveNo: 3,
  },
  {
    id: v4(),
    difficulty: "Very Easy",
    bonus: 1,
    title: "Add your first dice",
    desc: "Double down",
    completed: false,
    achieveNo: 4,
  },
  {
    id: v4(),
    difficulty: "Easy",
    bonus: 3,
    title: "Posess $1000",
    desc: "Still less than the stimulus check",
    completed: false,
    achieveNo: 5,
  },
  {
    id: v4(),
    difficulty: "Easy",
    bonus: 3,
    title: "Roll 100x",
    desc: "Just press the button 100 times",
    completed: false,
    achieveNo: 6,
  },
  {
    id: v4(),
    difficulty: "Easy",
    bonus: 3,
    title: "Upgrade a die to a d6",
    desc: "The classic",
    completed: false,
    achieveNo: 7,
  },
  {
    id: v4(),
    difficulty: "Easy",
    bonus: 3,
    title: "Roll your first double",
    desc: "Snake eyes?",
    completed: false,
    achieveNo: 8,
  },
  {
    id: v4(),
    difficulty: "Medium",
    bonus: 5,
    title: "Posess $10000",
    desc: "Almost minimum wage",
    completed: false,
    achieveNo: 9,
  },
  {
    id: v4(),
    difficulty: "Medium",
    bonus: 5,
    title: "Roll 1000x",
    desc: "Just press the button 1000 times",
    completed: false,
    achieveNo: 10,
  },
  {
    id: v4(),
    difficulty: "Medium",
    bonus: 5,
    title: "Roll your first triple",
    desc: "OH BABY A TRIPLE",
    completed: false,
    achieveNo: 11,
  },
  {
    id: v4(),
    difficulty: "Medium",
    bonus: 5,
    title: "Add your first multiplier die",
    desc: "It's a slippery slope from here",
    completed: false,
    achieveNo: 12,
  },
  {
    id: v4(),
    difficulty: "Hard",
    bonus: 8,
    title: "Roll your first quadruple",
    desc: "Most people can only tuple this high",
    completed: false,
    achieveNo: 13,
  },
  {
    id: v4(),
    difficulty: "Hard",
    bonus: 8,
    title: "Upgrade a die to a d12",
    desc: "Dodecahedron",
    completed: false,
    achieveNo: 14,
  },
  {
    id: v4(),
    difficulty: "Hard",
    bonus: 8,
    title: "Have 6 dice total",
    desc: "Land Grab",
    completed: false,
    achieveNo: 15,
  },
  {
    id: v4(),
    difficulty: "Hard",
    bonus: 8,
    title: "Posess $100000",
    desc: "Big Spender",
    completed: false,
    achieveNo: 16,
  },
  {
    id: v4(),
    difficulty: "Very Hard",
    bonus: 10,
    title: "Upgrade a die to a d20",
    desc: "Roll the basics",
    completed: false,
    achieveNo: 17,
  },
  {
    id: v4(),
    difficulty: "Very Hard",
    bonus: 10,
    title: "Posess $10000000",
    desc: "High Roller",
    completed: false,
    achieveNo: 18,
  },
  {
    id: v4(),
    difficulty: "Very Hard",
    bonus: 10,
    title: "Have 9 dice total",
    desc: "Fill the board",
    completed: false,
    achieveNo: 19,
  },
  {
    id: v4(),
    difficulty: "Very Hard",
    bonus: 10,
    title: "Roll your first quintuple",
    desc: "Hit the road, jackpot",
    completed: false,
    achieveNo: 20,
  },
  {
    id: v4(),
    difficulty: "Ultra Hard",
    bonus: 25,
    title: "Limit Breaker",
    desc: "Possess the maximum safe integer in Javascript, in cash",
    completed: false,
    achieveNo: 21,
  },
  {
    id: v4(),
    difficulty: "Ultra Hard",
    bonus: 25,
    title: "Possession is 9/10 of the law",
    desc: "Buy everything",
    completed: false,
    achieveNo: 22,
  },
  {
    id: v4(),
    difficulty: "Ultra Hard",
    bonus: 25,
    title: "Roll your first sextuple",
    desc: "It's not as dirty as it sounds",
    completed: false,
    achieveNo: 23,
  },
];
